roomrezsystem/log/urls.py
from django.urls import path
from .views import *
from .import views

urlpatterns = [
    path('', LogList.as_view(), name='log_list'),
    path('using/', LogList_using.as_view(), name='log_list_using'),
    path('reserve/', ReserveTeacher.as_view(), name='reserve_teacher'), 
    #path('reserve/<int:rid>/', ReserveRoom.as_view(), name='reserve_room'), 
    path('reserve/<int:tid>/<int:rid>/', ReserveLog.as_view(), name='reserve_log'),
    path('reverseroom/<int:rid>', Reverseroom.as_view(),name='reverse_room'),
    path('end/', EndRoom.as_view(), name='end_room'), 
    path('end/<int:lid>/', EndLog.as_view(), name='end_log'),
]

roomrezsystem/roomrezsystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html', extra_context={'title':'歡迎光臨'}), name='home'),
    path('user/', include('django.contrib.auth.urls')),
    path('developer', TemplateView.as_view(template_name='developer.html')),
    path('teacher/', include('teacher.urls')),
    path('room/', include('room.urls')),
    path('student/', include('student.urls')),
    path('classes/', include('classes.urls')),
    path('log/', include('log.urls')),
    path('check/',include('check.urls')),
    path('user/', include('user.urls')),

]

# 加入靜態檔案的處理規則
urlpatterns += static(
    settings.STATIC_URL, 
    document_root=settings.STATIC_ROOT
)

# 加入使用者上傳檔案的處理規則
urlpatterns += static(
    settings.MEDIA_URL, 
    document_root=settings.MEDIA_ROOT
)

roomrezsystem/teacher/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', TeacherList.as_view(), name='teacher_list'), 
    path('add/', TeacherAdd.as_view(), name='teacher_add'),
    path('<int:pk>/', TeacherView.as_view(), name='teacher_view'), 
    path('<int:pk>/edit/', TeacherEdit.as_view(), name='teacher_edit'),
    path('<int:pk>/delete/', TeacherDelete.as_view(), name='teacher_delete'),
]

roomrezsystem/log/models.py
from django.db.models import *
from teacher.models import *
from room.models import *
from teacher.models import Teacher
from classes.models import *
from student.models import *

# Create your models here.
class Log(Model):
    ST_OPTIONS = [
        (0,'即將使用'),
        (1,'使用中'),
        (2,'使用完畢')
    ]
    
    teacher = ForeignKey(Teacher, CASCADE)
    room = ForeignKey(Room, CASCADE)
    classes = ForeignKey(Classes, CASCADE)
    reserve = DateTimeField('登記時間', null=True)
    end = DateTimeField('結束使用時間', null=True)   
    workstatus = IntegerField('資料狀態', default=0 , choices=ST_OPTIONS)

    
    def __str__(self):
        return "{} | {} | {}".format(
            self.reserve, 
            self.teacher.realname, 
            self.room.name,
            self.classes.name
        )

roomrezsystem/teacher/models.py
from cgi import test
from operator import mod
from django.db import models
from classes.models import *
from student.models import *

# Create your models here.

class Teacher(Model):
    realname = CharField('姓名', max_length=32)
    #tea_classes = ManyToManyField(Classes,through='Teacher_Classes')
    #classes=models.ManyToManyField(Classes)
    tea_classes=models.ManyToManyField(Classes)
    tel = CharField('連絡電話', max_length=10)
    role= CharField('職稱', max_length=20)  #ex:訓育組長、教務主任、高中部數學老師
    cardid= CharField('卡號', max_length=30)
    def __str__(self):
        return "{} / {} / {}".format(
            self.realname, 
            self.tel, 
            self.role
        )

'''class  Teacher_Classes(Model):
    classes=ForeignKey(Classes,CASCADE)
    teacher=ForeignKey(Teacher,CASCADE)'''

roomrezsystem/teacher/views.py
from django.urls import reverse_lazy
from django.views.generic import *
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import *

# Create your views here.
class TeacherList(LoginRequiredMixin, ListView):    
    model = Teacher
    ordering = ['realname']    
    paginate_by = 20

class TeacherView(LoginRequiredMixin, DetailView):   
    model = Teacher
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        classes=Teacher.objects.filter(id=self.kwargs['pk'])
        tea_classes=classes[0]
        context['tea_classes']=tea_classes.tea_classes.all
        return context
class TeacherAdd(LoginRequiredMixin, CreateView):    
    model = Teacher
    fields = 'realname','tel','role','cardid'
    template_name = 'form.html'
    success_url = reverse_lazy('teacher_list')

class TeacherEdit(LoginRequiredMixin, UpdateView):   
    model = Teacher
    fields = 'realname','tel','role','cardid'
    template_name = 'form.html'
    success_url = reverse_lazy('teacher_list')

class TeacherDelete(LoginRequiredMixin, DeleteView): 
    model = Teacher
    template_name = 'confirm_delete.html'
    success_url = reverse_lazy('teacher_list')

roomrezsystem/templates/teacher/teacher_detail.html
{% extends "base.html" %}

{% block content %}
<div id="teacher-detail">
  <div class="teacher-detail">
    <div class="infor">
      <!--教師資訊 S-->
      <div class="tea-job-area">
        <div class="tea-card-header">
          {{ teacher.realname }}
        </div>
        <table class="tea-job-table">
          <tr>
            <th>連絡電話</th>
            <td>{{ teacher.tel }}</td>
          </tr>
          <tr>
            <th>卡號</th>
            <td>{{ teacher.cardid }}</td>
          </tr>
          <tr>
            <th>職稱</th>
            <td>{{ teacher.role }}</td>
          </tr>
        </table>
      </div>
      <!--教師資訊 E-->  
          <div class="tea-class-area">
              <div class="tea-card-header">
                <th>任教班級</th>
              </div>
              
            <table class="table table-sm">
              <tr>
                  {% for classes_list in tea_classes %}
                  <tr>
                  <td>
                    <a href="{% url 'classes_view' classes_list.id %}">
                    {{ classes_list }}</td>
                  </tr>
                  {% endfor %}
              </tr>
            </table>
          </div>
    </div>
          <!--借用紀錄 s-->
            <div class="tea-log-area">
              <div class="tea-card-header">
              <th>借用紀錄</th>
              </div>
                <div class="loglist">
                  <table>
                    <tr class="log">
                        {% for log in teacher.log_set.all %}
                          <tr class="log">
                            <td class="class">
                              <a href="{% url 'room_view' log.room.id %}">
                              {{ log.room.name }}
                              </a>
                            </td>
                            <td class="name">
                              {{ log.teacher.realname }}
                            </td>
                            <td class="time">{{ log.reserve|date:"Y/m/d H:i" }}</td>
                            <td class="time">{{ log.end|date:"Y/m/d H:i" }}</td>
                          </tr>
                        {% endfor %} 
                    </tr>
                  </table>
                </div>
            </div>
            <!--借用紀錄 e-->
  </div>
</div>
{% endblock %}

roomrezsystem/templates/teacher/teacher_list.html
{% extends "base.html" %}

{% block content %}
<style>
.collapse .nav-teacher{
    background-color: rgb(103, 196, 252);
}
</style>
<div class="teacher-container">
  <div class="mb-1">
    <a href="{% url 'teacher_add' %}" class="btn btn-sm btn-primary">
      <i class="fas fa-user-plus"></i> 新增教師
    </a>
  </div>

  <div class="teacher-list">
    <ul class="table table-sm">

      <li class="table-header">
        <div class="item">姓名</div>
        <div class="item">電話</div>
        <div class="item">卡號</div>
        <div class="item">職稱</div>
        <div class="item">操作</div>
      </li>

      
      {% for teacher in teacher_list %}
        <li class="table-row">
          <div class="item">
            <a href="{% url 'teacher_view' teacher.id %}">{{ teacher.realname }}</a>
          </div>
          <div class="item">{{ teacher.tel }}</div>
          <div class="item">{{ teacher.cardid }}</div>
          <div class="item">{{ teacher.role }}</div>
          <div class="item">
            <a href="{% url 'teacher_delete' teacher.id %}" class="btn btn-sm btn-danger">刪除</a>
            <a href="{% url 'teacher_edit' teacher.id %}" class="btn btn-sm btn-primary">修改</a>
          </div>
        </li>
      {% endfor %}
      

    </ul>
  </div>

</div>
{% endblock %}