roomrezsystem/classes/urls.py
from django import views
from django.urls import path
from .views import *
from . import views

urlpatterns = [
    path('', ClassesList.as_view(), name='classes_list'),
    path('add/', ClassesAdd.as_view(), name='classes_add'), 
    path('<int:pk>/stu_relate',ClassesRelateStudentList.as_view(),name='classes_stu_relate'),
    path('<int:pk>/tea_relate',ClassesRelateTeacherList.as_view(),name='classes_tea_relate'),
    path('<int:pk>/stu_relate/<int:stu>', views.ClassesManytomanyForStudent,name='classes_relate_student'),
    path('<int:pk>/tea_relate/<int:tea>', views.ClassesManytomanyForTeacher,name='classes_relate_teacher'),
    path('<int:pk>/', ClassesView.as_view(), name='classes_view'),
    path('<int:pk>/edit/', ClassesEdit.as_view(), name='classes_edit'),
    path('<int:pk>/delete/', ClassesDelete.as_view(), name='classes_delete'),
]

roomrezsystem/log/urls.py
from django.urls import path
from .views import *
from .import views

urlpatterns = [
    path('', LogList.as_view(), name='log_list'),
    path('using/', LogList_using.as_view(), name='log_list_using'),
    path('reserve/', ReserveTeacher.as_view(), name='reserve_teacher'), 
    #path('reserve/<int:rid>/', ReserveRoom.as_view(), name='reserve_room'), 
    path('reserve/<int:tid>/<int:rid>/', ReserveLog.as_view(), name='reserve_log'),
    path('reverseroom/<int:rid>', Reverseroom.as_view(),name='reverse_room'),
    path('end/', EndRoom.as_view(), name='end_room'), 
    path('end/<int:lid>/', EndLog.as_view(), name='end_log'),
]

roomrezsystem/roomrezsystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html', extra_context={'title':'歡迎光臨'}), name='home'),
    path('user/', include('django.contrib.auth.urls')),
    path('developer', TemplateView.as_view(template_name='developer.html')),
    path('teacher/', include('teacher.urls')),
    path('room/', include('room.urls')),
    path('student/', include('student.urls')),
    path('classes/', include('classes.urls')),
    path('log/', include('log.urls')),
    path('check/',include('check.urls')),
    path('user/', include('user.urls')),

]

# 加入靜態檔案的處理規則
urlpatterns += static(
    settings.STATIC_URL, 
    document_root=settings.STATIC_ROOT
)

# 加入使用者上傳檔案的處理規則
urlpatterns += static(
    settings.MEDIA_URL, 
    document_root=settings.MEDIA_ROOT
)

roomrezsystem/classes/models.py
from django.db.models import *

# Create your models here.
class Classes(Model):
    name = CharField('班級名稱', max_length=30)

    def __str__(self):
        return "{}".format(
            self.name
        )

roomrezsystem/student/models.py
from re import M
from statistics import mode
from django.db.models import *
from classes.models import *
from django.db import models

from classes.models import *

# Create your models here.
class Student(Model):
    realname = CharField('姓名', max_length=32)
    stu_classes = models.ManyToManyField(Classes,through='Student_Classes')
    cardid= CharField('卡號', max_length=30)
    def __str__(self):
        return "{} / {} / {}".format(
            self.realname, 
            self.stu_classes, 
            self.cardid
        )

class Student_Classes(Model):
    classes=models.ForeignKey(Classes,CASCADE)
    student=models.ForeignKey(Student,CASCADE)

roomrezsystem/teacher/models.py
from cgi import test
from operator import mod
from django.db import models
from classes.models import *
from student.models import *

# Create your models here.

class Teacher(Model):
    realname = CharField('姓名', max_length=32)
    #tea_classes = ManyToManyField(Classes,through='Teacher_Classes')
    #classes=models.ManyToManyField(Classes)
    tea_classes=models.ManyToManyField(Classes)
    tel = CharField('連絡電話', max_length=10)
    role= CharField('職稱', max_length=20)  #ex:訓育組長、教務主任、高中部數學老師
    cardid= CharField('卡號', max_length=30)
    def __str__(self):
        return "{} / {} / {}".format(
            self.realname, 
            self.tel, 
            self.role
        )

'''class  Teacher_Classes(Model):
    classes=ForeignKey(Classes,CASCADE)
    teacher=ForeignKey(Teacher,CASCADE)'''

roomrezsystem/classes/views.py
from urllib import request
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.urls import reverse
from django.views.generic import *
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import *
from student.models import *
from django.db import *
from teacher.models import *

# Create your views here.

class ClassesList(LoginRequiredMixin, ListView):   
    model = Classes    
    paginate_by = 20


class ClassesView(LoginRequiredMixin, DetailView): 
    model = Classes

    ordering = ['name']    
    paginate_by = 20
    
    def get_queryset(self):
        return Classes.objects.prefetch_related('student_set','teacher_set')
        

class ClassesAdd(LoginRequiredMixin, CreateView):  
    model = Classes
    fields = '__all__'
    template_name = 'form.html'
    success_url = reverse_lazy('classes_list')

class ClassesEdit(LoginRequiredMixin, UpdateView): 
    model = Classes
    fields = '__all__'
    template_name = 'form.html'
    success_url = reverse_lazy('classes_list')

class ClassesDelete(LoginRequiredMixin, DeleteView):   
    model = Classes
    template_name = 'confirm_delete.html'
    success_url = reverse_lazy('classes_list')

class ClassesRelateStudentList(LoginRequiredMixin,ListView):
    model= Student
    template_name = 'classes/stu_relate.html'
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        classes=Classes.objects.filter(id=self.kwargs['pk'])
        context['choosen_classes']=classes[0]
        return context

class ClassesRelateTeacherList(LoginRequiredMixin,ListView):
    model= Teacher
    template_name = 'classes/tea_relate.html'
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        classes=Classes.objects.filter(id=self.kwargs['pk'])
        context['choosen_classes']=classes[0]
        return context


def ClassesManytomanyForStudent(reqeust,pk,stu):

    choosen_students=Student.objects.get(id=stu)
    choosen_classes=Classes.objects.get(id=pk)
    choosen_students.stu_classes.add(choosen_classes)
    #choosen_class=Classes
    #choosen_students=Student(realname='gg',cardid='123')
    #choosen_students.save()
    #choosen_student=Student.objects.filter(id=stu).classes.add(choosen_classes)
    #for choosen_student in choosen_students:
        #choosen_student.stu_classes.add(choosen_classes[0])
    #for choosen_student in choosen_students:
        
    return redirect(reverse('classes_view',args=str(pk)))

def ClassesManytomanyForTeacher(reqeust,pk,tea):

    choosen_teachers=Teacher.objects.get(id=tea)
    choosen_classes=Classes.objects.get(id=pk)
    choosen_teachers.tea_classes.add(choosen_classes)
    #choosen_class=Classes
    #choosen_teacher=Teacher(realname='hentai',cardid='6969')
    #choosen_teacher.save()
    #choosen_class=choosen_classes[0]
    #choosen_teacher.classes.add(choosen_class)
    #choosen_student=Student.objects.filter(id=stu).classes.add(choosen_classes)
    #for choosen_teacher in choosen_teachers:
        #choosen_teacher.classes.set(choosen_classes)
        #choosen_teacher.tea_classes.add(choosen_classes[0])
    #for choosen_student in choosen_students:
        
    return redirect(reverse('classes_view',args=str(pk)))

roomrezsystem/templates/classes/classes_detail.html
{% extends "base.html" %}

{% block content %}
<div class="class-container">
  <div class="class-mb-2">
    <a href="{% url 'classes_edit' classes.id %}" class="btn btn-sm btn-primary">
      <i class="fas fa-edit"></i> 修改
    </a>
    <a href="{% url 'classes_delete' classes.id %}" class="btn btn-sm btn-danger">
      <i class="fas fa-trash"></i> 刪除
    </a>
  </div>
  <div class="class-detail">
        <div class="card-header">{{ classes.name }}</div>
        <ul class="class-table">
            <li class="table-header">
            <div class="item">班級老師</div>
            <div class="item">卡號</div>
            <div class="btn"><a href="{% url 'classes_tea_relate' classes.id  %}"><i class="fas fa-user-plus"></i> 新增老師</a></div>
            </li>
              {% for teacher in classes.teacher_set.all %}
              <li class="table-row">
                  <div class="item"><a href="{% url 'teacher_view' teacher.id %}">{{teacher.realname}}  </a></div>
                  <div class="item">{{teacher.cardid}}</div>
                  <div class="btn"></div>
              </li>
              {% endfor %} 
        </ul>
        <ul class="class-table">
            <li class="table-header">
            <div class="item">班級學生</div>
            <div class="item">卡號</div>
            <div class="btn"><a href="{% url 'classes_stu_relate' classes.id  %}"><i class="fas fa-user-plus"></i> 新增學生</a></div>
            </li>
              {% for student in classes.student_set.all %}
              <li class="table-row">
                  <div class="item"><a href="{% url 'student_view' student.id %}">{{student.realname}}  </a></div>
                  <div class="item">{{student.cardid}}</div>
                  <div class="btn"></div>
              </li>
              {% endfor %} 
        </ul>
  </div>
</div>
{% endblock %}

roomrezsystem/templates/classes/classes_list.html
{% extends "base.html" %}

{% block content %}
<style>
.collapse .nav-classes{
    background-color: rgb(170, 170, 170);
}
</style>

<div class="mb-1">
  <a href="{% url 'classes_add' %}" class="btn btn-sm btn-primary">
    <i class="fas fa-plus"></i> 新增班級
  </a>
</div>

<div id="classes-list" class="classes">

  {% for classes in classes_list %}
    <div class="card shadow-sm" onclick="location.href='{% url 'classes_view' classes.id %}';" style="cursor:pointer;">
        <div class="card-title" >
          <a href="{% url 'classes_view' classes.id %}">{{ classes.name }}</a>
        </div>

        <img src="https://imgur.dcard.tw/CRxTlNOh.jpg">
       
    </div>
  
  
    
  {% endfor %}
</div>
{% endblock %}

roomrezsystem/templates/classes/stu_relate.html
{% extends "base.html" %}

{% block content %}

<div class="student-list">
  <ul class="table table">
  {% for student in student_list %}
    
        <li class="table-row">
          <div class="item" ><a href="{% url 'classes_relate_student' choosen_classes.id student.id %}">{{ student.realname }}</a></div>
          <div class="item" style="color:black;">{{ student.cardid }}</div>
        </li>

    <!--
    <div class="card shadow-sm">

        <div class="card-body">
        <div class="card-title">
            <a href="{% url 'classes_relate_student' choosen_classes.id student.id %}">{{ student.realname }}</a>
        </div>
        <div class="card-text">{{ student.cardid }}</div>
        </div>
    </div>-->
  {% endfor %}
  </ul>
</div>

{% endblock %}

roomrezsystem/templates/classes/tea_relate.html
{% extends "base.html" %}

{% block content %}

<div id="teacher-list" class="card-group">
  {% for teacher in teacher_list %}
  
    <div class="card shadow-sm">

        <div class="card-body">
        <div class="card-title">
            <a href="{% url 'classes_relate_teacher' choosen_classes.id teacher.id %}">{{ teacher.realname }}</a>
        </div>
        <div class="card-text">{{ teacher.cardid }}</div>
        </div>
    </div>
  {% endfor %}
</div>

{% endblock %}